language: python
cache: pip

python:
  - "3.6"
  - "3.5"

env:
  - TOXENV=django.1.11
  - TOXENV=django.2.0
  - TOXENV=django.2.1

matrix:
  fast_finish: true
  include:
      - { python: "2.7", env: TOXENV=django.1.11 }

install:
  - pip install tox

script:
  - tox
