language: python
cache: pip
dist: bionic
sudo: false
arch:
  - amd64
  - ppc64le
python:
  - 3.6
  - 3.7
  - 3.8

install:
  - apt-get install build-essential libssl-dev libffi-dev \
    python3-dev cargo
  - python -m pip install -U pip
  - pip install tox tox-travis

script:
  - tox -r
