# Generated by Django 3.2.18 on 2023-03-26 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('functional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedroutermixinusermodel',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
